"""create core planning tables

Revision ID: 974c1177959f
Revises: 
Create Date: 2026-09-10 20:46:44.313148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974c1177959f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.Enum('TRACK', 'SIGNAL', 'OHE', 'POINT_MACHINE', 'LEVEL_CROSSING', 'OTHER', name='asset_type'), nullable=False),
    sa.Column('department', sa.Enum('ENGINEERING', 'SNT', 'TRACTION', name='department'), nullable=False),
    sa.Column('corridor_id', sa.String(length=50), nullable=False),
    sa.Column('location_start', sa.Float(), nullable=False),
    sa.Column('location_end', sa.Float(), nullable=False),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('operational_importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_corridor_id'), 'assets', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_assets_department'), 'assets', ['department'], unique=False)
    op.create_table('block_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('corridor_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('block_type', sa.Enum('TRAFFIC_BLOCK', 'POWER_BLOCK', 'LINE_BLOCK', 'COMBINED_BLOCK', name='block_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RECOMMENDED', 'APPROVED', 'COMPLETED', 'CANCELLED', name='block_plan_status'), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('utilization_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_plans_corridor_id'), 'block_plans', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_block_plans_plan_code'), 'block_plans', ['plan_code'], unique=True)
    op.create_index(op.f('ix_block_plans_plan_date'), 'block_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_block_plans_status'), 'block_plans', ['status'], unique=False)
    op.create_table('block_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('block_type', sa.Enum('TRAFFIC_BLOCK', 'POWER_BLOCK', 'LINE_BLOCK', 'COMBINED_BLOCK', name='block_type'), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('maximum_duration_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_windows_available'), 'block_windows', ['available'], unique=False)
    op.create_index(op.f('ix_block_windows_corridor_id'), 'block_windows', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_block_windows_date'), 'block_windows', ['date'], unique=False)
    op.create_table('goods_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_window_start', sa.Time(), nullable=False),
    sa.Column('time_window_end', sa.Time(), nullable=False),
    sa.Column('expected_goods_trains', sa.Integer(), nullable=False),
    sa.Column('traffic_density', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='traffic_density'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_forecasts_corridor_id'), 'goods_forecasts', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_goods_forecasts_date'), 'goods_forecasts', ['date'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sa.String(length=50), nullable=False),
    sa.Column('department', sa.Enum('ENGINEERING', 'SNT', 'TRACTION', name='department'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_department'), 'resources', ['department'], unique=False)
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('train_type', sa.Enum('EXPRESS', 'PASSENGER', 'FREIGHT', 'LOCAL', 'SPECIAL', name='train_type'), nullable=False),
    sa.Column('corridor_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('traffic_category', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_corridor_id'), 'trains', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_trains_end_time'), 'trains', ['end_time'], unique=False)
    op.create_index(op.f('ix_trains_start_time'), 'trains', ['start_time'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('ENGINEERING', 'SNT', 'TRACTION', name='department'), nullable=False),
    sa.Column('corridor_id', sa.String(length=50), nullable=False),
    sa.Column('location_start', sa.Float(), nullable=False),
    sa.Column('location_end', sa.Float(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('safety_impact', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('failure_risk', sa.Float(), nullable=False),
    sa.Column('availability_impact', sa.Float(), nullable=False),
    sa.Column('required_block_type', sa.Enum('TRAFFIC_BLOCK', 'POWER_BLOCK', 'LINE_BLOCK', 'COMBINED_BLOCK', name='block_type'), nullable=False),
    sa.Column('required_resources', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'COMPLETED', 'OVERDUE', 'EMERGENCY', name='task_status'), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_asset_id'), 'maintenance_tasks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_corridor_id'), 'maintenance_tasks', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_department'), 'maintenance_tasks', ['department'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_due_at'), 'maintenance_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_priority_level'), 'maintenance_tasks', ['priority_level'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_source_system'), 'maintenance_tasks', ['source_system'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_status'), 'maintenance_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_task_code'), 'maintenance_tasks', ['task_code'], unique=True)
    op.create_table('block_plan_tasks',
    sa.Column('block_plan_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_task_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['block_plan_id'], ['block_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('block_plan_id', 'maintenance_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_plan_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_task_code'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_status'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_source_system'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_priority_level'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_due_at'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_department'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_corridor_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_asset_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_start_time'), table_name='trains')
    op.drop_index(op.f('ix_trains_end_time'), table_name='trains')
    op.drop_index(op.f('ix_trains_corridor_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_department'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_goods_forecasts_date'), table_name='goods_forecasts')
    op.drop_index(op.f('ix_goods_forecasts_corridor_id'), table_name='goods_forecasts')
    op.drop_table('goods_forecasts')
    op.drop_index(op.f('ix_block_windows_date'), table_name='block_windows')
    op.drop_index(op.f('ix_block_windows_corridor_id'), table_name='block_windows')
    op.drop_index(op.f('ix_block_windows_available'), table_name='block_windows')
    op.drop_table('block_windows')
    op.drop_index(op.f('ix_block_plans_status'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_plan_date'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_plan_code'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_corridor_id'), table_name='block_plans')
    op.drop_table('block_plans')
    op.drop_index(op.f('ix_assets_department'), table_name='assets')
    op.drop_index(op.f('ix_assets_corridor_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
